/* Generated By:JavaCC: Do not edit this line. AWKTreeConstants.java Version 5.0 */
public interface AWKTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJT$BEGIN_CURLY = 1;
  public int JJT$END_CURLY = 2;
  public int JJT$PATTERN = 3;
  public int JJT$ENDLINE = 4;
  public int JJT$BEGIN_PARENTHESIS = 5;
  public int JJT$END_PARENTHESIS = 6;
  public int JJT$IF = 7;
  public int JJT$ELSE = 8;
  public int JJT$WHILE = 9;
  public int JJT$DO = 10;
  public int JJT$FOR = 11;
  public int JJT$IN = 12;
  public int JJT$ID = 13;
  public int JJT$DELETE = 14;
  public int JJT$BEGIN_BRACKET = 15;
  public int JJT$END_BRACKET = 16;
  public int JJT$EXIT = 17;
  public int JJT$RETURN = 18;
  public int JJT$PRINT = 19;
  public int JJT$GETLINE = 20;
  public int JJT$COMMA = 21;
  public int JJT$VARIABLE = 22;
  public int JJT$ASSIGN = 23;
  public int JJT$QUESTION_MARK = 24;
  public int JJT$COLON = 25;
  public int JJT$AND_OR = 26;
  public int JJT$COMPARISON = 27;
  public int JJT$ARITHMETIC = 28;
  public int JJT$SINGLE_SIGN = 29;
  public int JJT$EXPO = 30;
  public int JJT$UNARY_OP = 31;
  public int JJT$CONSTANT = 32;


  public String[] jjtNodeName = {
    "PROGRAM",
    "$BEGIN_CURLY",
    "$END_CURLY",
    "$PATTERN",
    "$ENDLINE",
    "$BEGIN_PARENTHESIS",
    "$END_PARENTHESIS",
    "$IF",
    "$ELSE",
    "$WHILE",
    "$DO",
    "$FOR",
    "$IN",
    "$ID",
    "$DELETE",
    "$BEGIN_BRACKET",
    "$END_BRACKET",
    "$EXIT",
    "$RETURN",
    "$PRINT",
    "$GETLINE",
    "$COMMA",
    "$VARIABLE",
    "$ASSIGN",
    "$QUESTION_MARK",
    "$COLON",
    "$AND_OR",
    "$COMPARISON",
    "$ARITHMETIC",
    "$SINGLE_SIGN",
    "$EXPO",
    "$UNARY_OP",
    "$CONSTANT",
  };
}
/* JavaCC - OriginalChecksum=5d99d588002586f497efb46189c5aa1b (do not edit this line) */
