/* Generated By:JJTree&JavaCC: Do not edit this line. AWKTokenManager.java */

/** Token Manager. */
public class AWKTokenManager implements AWKConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7fffffffffc0L) != 0L)
         {
            jjmatchedKind = 47;
            return 1;
         }
         if ((active1 & 0x600L) != 0L)
         {
            jjmatchedKind = 52;
            return 27;
         }
         if ((active1 & 0x100L) != 0L)
            return 5;
         return -1;
      case 1:
         if ((active0 & 0x7fb5c79bffc0L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 47;
               jjmatchedPos = 1;
            }
            return 1;
         }
         if ((active0 & 0x4a38640000L) != 0L)
            return 1;
         return -1;
      case 2:
         if ((active0 & 0x7f95e499ff40L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 2;
            return 1;
         }
         if ((active0 & 0x2003020080L) != 0L)
            return 1;
         return -1;
      case 3:
         if ((active0 & 0xc0400900500L) != 0L)
            return 1;
         if ((active0 & 0x7391e409fa40L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 3;
            return 1;
         }
         return -1;
      case 4:
         if ((active0 & 0x211000004040L) != 0L)
            return 1;
         if ((active0 & 0x5281e409ba00L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 4;
            return 1;
         }
         return -1;
      case 5:
         if ((active0 & 0x1080a0000200L) != 0L)
            return 1;
         if ((active0 & 0x42014409b800L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
            return 1;
         }
         return -1;
      case 6:
         if ((active0 & 0x400040003800L) != 0L)
            return 1;
         if ((active0 & 0x20104098000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 6;
            return 1;
         }
         return -1;
      case 7:
         if ((active0 & 0x20004010000L) != 0L)
            return 1;
         if ((active0 & 0x100088000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
            return 1;
         }
         return -1;
      case 8:
         if ((active0 & 0x100088000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 8;
            return 1;
         }
         return -1;
      case 9:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 9;
            return 1;
         }
         if ((active0 & 0x100080000L) != 0L)
            return 1;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 36:
         return jjStopAtPos(0, 67);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 40:
         return jjStopAtPos(0, 62);
      case 41:
         return jjStopAtPos(0, 63);
      case 43:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400L);
      case 44:
         return jjStopAtPos(0, 66);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200L);
      case 58:
         return jjStopAtPos(0, 69);
      case 59:
         return jjStopAtPos(0, 5);
      case 63:
         return jjStopAtPos(0, 68);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x700L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x840L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x0L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x6080L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x78000L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x80000L, 0x0L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x600000L, 0x0L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x3800000L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x78000000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 64);
      case 93:
         return jjStopAtPos(0, 65);
      case 94:
         return jjStartNfaWithStates_0(0, 72, 5);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x20000000000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x8800000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x80400000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x400000000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x4200000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x40000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x200000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 60);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40L);
      case 125:
         return jjStopAtPos(0, 61);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         break;
      case 43:
         if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(1, 74);
         break;
      case 45:
         if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(1, 73);
         break;
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000040L, active1, 0L);
      case 70:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(1, 21, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000L, active1, 0L);
      case 71:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x118800L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x22080L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L, active1, 0L);
      case 82:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 22, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0x6004700L, active1, 0L);
      case 83:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(1, 18, 1);
         else if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L);
      case 84:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(1, 28, 1);
         break;
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x548000000000L, active1, 0L);
      case 102:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(1, 33, 1);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L, active1, 0L);
      case 110:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 38, 1);
         break;
      case 111:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(1, 35, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0x22000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x210000000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L);
      case 124:
         if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 68:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 1);
         break;
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x40008000L);
      case 71:
         return jjMoveStringLiteralDfa3_0(active0, 0x740L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x181800L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 82:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 83:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 24, 1);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(2, 25, 1);
         break;
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 88:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x281000000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 114:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 37, 1);
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x500000000000L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 67:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x2240L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 77:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x40004000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 84:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 1);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 86:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 101:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x401000000000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L);
      case 116:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 1);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 43, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x100008000L);
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 70:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 71:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 78:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x10200L);
      case 79:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x20082000L);
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 1);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x420000000000L);
      case 107:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 40, 1);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
      case 116:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 45, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 68:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 9, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 77:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x100002000L);
      case 80:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 1);
         break;
      case 84:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 87:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 39, 1);
         break;
      case 110:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 44, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x420000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 69:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 1);
         break;
      case 70:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      case 72:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 1);
         break;
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      case 77:
         return jjMoveStringLiteralDfa7_0(active0, 0x100010000L);
      case 78:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 1);
         break;
      case 84:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 1);
         break;
      case 101:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 46, 1);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x100080000L);
      case 68:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 69:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(7, 16, 1);
         break;
      case 79:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(7, 26, 1);
         break;
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 41, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 84:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(9, 19, 1);
         break;
      case 72:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000L);
      case 78:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(9, 32, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 83:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(10, 15, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 27;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 2);
                  else if (curChar == 61)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(3);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     jjCheckNAdd(24);
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0xac2000000000L & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(3, 5);
                  else if (curChar == 33)
                     jjCheckNAdd(12);
                  else if (curChar == 61)
                     jjCheckNAdd(12);
                  else if (curChar == 46)
                     jjCheckNAdd(3);
                  if ((0x280000000000L & l) != 0L)
                  {
                     if (kind > 52)
                        kind = 52;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 60)
                     jjCheckNAdd(12);
                  else if (curChar == 62)
                     jjCheckNAdd(12);
                  else if (curChar == 37)
                     jjCheckNAdd(5);
                  else if (curChar == 42)
                     jjCheckNAdd(5);
                  else if (curChar == 47)
                     jjCheckNAdd(5);
                  else if (curChar == 61)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  if (curChar == 43)
                     jjCheckNAdd(5);
                  else if (curChar == 45)
                     jjCheckNAdd(5);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if (curChar == 46)
                     jjCheckNAdd(3);
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if (curChar == 61 && kind > 50)
                     kind = 50;
                  break;
               case 5:
                  if (curChar == 61 && kind > 50)
                     kind = 50;
                  break;
               case 6:
                  if (curChar == 45)
                     jjCheckNAdd(5);
                  break;
               case 7:
                  if (curChar == 43)
                     jjCheckNAdd(5);
                  break;
               case 8:
                  if (curChar == 47)
                     jjCheckNAdd(5);
                  break;
               case 9:
                  if (curChar == 42)
                     jjCheckNAdd(5);
                  break;
               case 10:
                  if (curChar == 37)
                     jjCheckNAdd(5);
                  break;
               case 12:
                  if (curChar == 61 && kind > 51)
                     kind = 51;
                  break;
               case 13:
                  if (curChar == 62)
                     jjCheckNAdd(12);
                  break;
               case 14:
                  if ((0x5000000000000000L & l) != 0L && kind > 51)
                     kind = 51;
                  break;
               case 15:
                  if (curChar == 61)
                     jjCheckNAdd(12);
                  break;
               case 16:
                  if (curChar == 33)
                     jjCheckNAdd(12);
                  break;
               case 17:
                  if (curChar == 60)
                     jjCheckNAdd(12);
                  break;
               case 18:
                  if ((0xac2000000000L & l) != 0L && kind > 53)
                     kind = 53;
                  break;
               case 19:
                  if (curChar == 34)
                     jjCheckNAddStates(3, 5);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 21:
                  if ((0xfc00ffff00000000L & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 22:
                  if (curChar == 34 && kind > 54)
                     kind = 54;
                  break;
               case 23:
                  if ((0x280000000000L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  jjCheckNAddStates(0, 2);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAdd(24);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 2);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     jjCheckNAdd(1);
                  }
                  else if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(1);
                  break;
               case 11:
                  if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 20:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 21:
                  if ((0x78000001f8000001L & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 27 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   24, 25, 2, 20, 21, 22, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\73", "\102\105\107\111\116", "\105\116\104", 
"\101\122\107\103", "\101\122\107\111\116\104", "\101\122\107\126", 
"\102\111\116\115\117\104\105", "\103\117\116\126\106\115\124", "\105\116\126\111\122\117\116", 
"\105\122\122\116\117", "\106\111\105\114\104\127\111\104\124\110\123", 
"\106\111\114\105\116\101\115\105", "\106\116\122", "\106\123", "\111\107\116\117\122\105\103\101\123\105", 
"\114\111\116\124", "\116\106", "\116\122", "\117\106\115\124", "\117\106\123", "\117\122\123", 
"\120\122\117\103\111\116\106\117", "\122\123", "\122\124", "\122\123\124\101\122\124", 
"\122\114\105\116\107\124\110", "\123\125\102\123\105\120", "\124\105\130\124\104\117\115\101\111\116", 
"\151\146", "\145\154\163\145", "\144\157", "\167\150\151\154\145", "\146\157\162", 
"\151\156", "\144\145\154\145\164\145", "\142\162\145\141\153", 
"\143\157\156\164\151\156\165\145", "\156\145\170\164", "\145\170\151\164", "\162\145\164\165\162\156", 
"\160\162\151\156\164", "\147\145\164\154\151\156\145", null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\173", "\175", "\50", "\51", "\133", "\135", "\54", 
"\44", "\77", "\72", "\174\174", "\46\46", "\136", "\55\55", "\53\53", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xf07fffffffffffe1L, 0x7ffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[27];
static private final int[] jjstateSet = new int[54];
static protected char curChar;
/** Constructor. */
public AWKTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public AWKTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 27; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
