/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected AWK parser;
  protected int line;
  protected int column;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(AWK p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  public void jjtSetLine(int line) { this.line = line; }
  public int jjtGetLine() { return this.line; }

  public void jjtSetColumn(int column) { this.column = column; }
  public int jjtGetColumn() { return this.column; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { 
	return AWKTreeConstants.jjtNodeName[id].substring(1);
  }
  public String toString(String prefix) { return prefix + toString(); }

  private boolean isPrintable() {
	if (AWKTreeConstants.jjtNodeName[id].charAt(0) == '$')
	  return true;
	return false;
  }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
	if (isPrintable()) {
		System.out.format("@(%03d,%03d) %20s = %s\n", this.jjtGetLine(), this.jjtGetColumn(), this.toString(prefix), this.jjtGetValue());
	}
    
	if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
			n.dump(prefix);
        }
      }
    }
  }
}

/* JavaCC - OriginalChecksum=1f1417eaa790dc87886fdc728b873122 (do not edit this line) */
