all:
	pdflatex -jobname "Relatorio2-grupo2-turmaB" -output-directory ./output/ ./main.tex

clean:
	rm -rf ./*~
	rm -rf ./input/*~
	rm -rf ./output/*.aux
	rm -rf ./output/*.log
	rm -rf ./output/*.toc
	rm -rf ./output/*.out

