/* Generated By:JJTree&JavaCC: Do not edit this line. AWKConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AWKConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENDLINE = 5;
  /** RegularExpression Id. */
  int BEGIN = 6;
  /** RegularExpression Id. */
  int END = 7;
  /** RegularExpression Id. */
  int ARGC = 8;
  /** RegularExpression Id. */
  int ARGIND = 9;
  /** RegularExpression Id. */
  int ARGV = 10;
  /** RegularExpression Id. */
  int BINMODE = 11;
  /** RegularExpression Id. */
  int CONVFMT = 12;
  /** RegularExpression Id. */
  int ENVIRON = 13;
  /** RegularExpression Id. */
  int ERRNO = 14;
  /** RegularExpression Id. */
  int FIELDWIDTHS = 15;
  /** RegularExpression Id. */
  int FILENAME = 16;
  /** RegularExpression Id. */
  int FNR = 17;
  /** RegularExpression Id. */
  int FS = 18;
  /** RegularExpression Id. */
  int IGNORECASE = 19;
  /** RegularExpression Id. */
  int LINT = 20;
  /** RegularExpression Id. */
  int NF = 21;
  /** RegularExpression Id. */
  int NR = 22;
  /** RegularExpression Id. */
  int OFMT = 23;
  /** RegularExpression Id. */
  int OFS = 24;
  /** RegularExpression Id. */
  int ORS = 25;
  /** RegularExpression Id. */
  int PROCINFO = 26;
  /** RegularExpression Id. */
  int RS = 27;
  /** RegularExpression Id. */
  int RT = 28;
  /** RegularExpression Id. */
  int RSTART = 29;
  /** RegularExpression Id. */
  int RLENGTH = 30;
  /** RegularExpression Id. */
  int SUBSEP = 31;
  /** RegularExpression Id. */
  int TEXTDOMAIN = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int DO = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int FOR = 37;
  /** RegularExpression Id. */
  int IN = 38;
  /** RegularExpression Id. */
  int DELETE = 39;
  /** RegularExpression Id. */
  int BREAK = 40;
  /** RegularExpression Id. */
  int CONTINUE = 41;
  /** RegularExpression Id. */
  int NEXT = 42;
  /** RegularExpression Id. */
  int EXIT = 43;
  /** RegularExpression Id. */
  int RETURN = 44;
  /** RegularExpression Id. */
  int PRINT = 45;
  /** RegularExpression Id. */
  int GETLINE = 46;
  /** RegularExpression Id. */
  int ID = 47;
  /** RegularExpression Id. */
  int INTEGER = 48;
  /** RegularExpression Id. */
  int FLOAT = 49;
  /** RegularExpression Id. */
  int ASSIGN = 50;
  /** RegularExpression Id. */
  int COMPARISON = 51;
  /** RegularExpression Id. */
  int SINGLE_SIGN = 52;
  /** RegularExpression Id. */
  int ARITHMETIC = 53;
  /** RegularExpression Id. */
  int STRING = 54;
  /** RegularExpression Id. */
  int CHAR = 55;
  /** RegularExpression Id. */
  int ALPHA_NUMERIC = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;
  /** RegularExpression Id. */
  int SYMBOL = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"ARGC\"",
    "\"ARGIND\"",
    "\"ARGV\"",
    "\"BINMODE\"",
    "\"CONVFMT\"",
    "\"ENVIRON\"",
    "\"ERRNO\"",
    "\"FIELDWIDTHS\"",
    "\"FILENAME\"",
    "\"FNR\"",
    "\"FS\"",
    "\"IGNORECASE\"",
    "\"LINT\"",
    "\"NF\"",
    "\"NR\"",
    "\"OFMT\"",
    "\"OFS\"",
    "\"ORS\"",
    "\"PROCINFO\"",
    "\"RS\"",
    "\"RT\"",
    "\"RSTART\"",
    "\"RLENGTH\"",
    "\"SUBSEP\"",
    "\"TEXTDOMAIN\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"for\"",
    "\"in\"",
    "\"delete\"",
    "\"break\"",
    "\"continue\"",
    "\"next\"",
    "\"exit\"",
    "\"return\"",
    "\"print\"",
    "\"getline\"",
    "<ID>",
    "<INTEGER>",
    "<FLOAT>",
    "<ASSIGN>",
    "<COMPARISON>",
    "<SINGLE_SIGN>",
    "<ARITHMETIC>",
    "<STRING>",
    "<CHAR>",
    "<ALPHA_NUMERIC>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"$\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"^\"",
    "\"--\"",
    "\"++\"",
  };

}
