/* Generated By:JavaCC: Do not edit this line. AWKTreeConstants.java Version 5.0 */
public interface AWKTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTINSTRUCTION = 1;
  public int JJT$BEGIN_CURLY = 2;
  public int JJT$END_CURLY = 3;
  public int JJT$PATTERN = 4;
  public int JJTACTION = 5;
  public int JJTSTATEMENT = 6;
  public int JJT$ENDLINE = 7;
  public int JJTCOMMAND = 8;
  public int JJT$BEGIN_PARENTHESIS = 9;
  public int JJT$END_PARENTHESIS = 10;
  public int JJT$IF = 11;
  public int JJT$ELSE = 12;
  public int JJT$WHILE = 13;
  public int JJT$DO_WHILE = 14;
  public int JJT$DO = 15;
  public int JJT$FOR = 16;
  public int JJT$FOR_SEPARATOR = 17;
  public int JJT$IN = 18;
  public int JJT$ID = 19;
  public int JJTDELETE = 20;
  public int JJT$DELETE = 21;
  public int JJT$BEGIN_BRACKET = 22;
  public int JJT$END_BRACKET = 23;
  public int JJT$EXIT = 24;
  public int JJT$RETURN = 25;
  public int JJT$PRINT = 26;
  public int JJT$GETLINE = 27;
  public int JJTEXPR_LIST = 28;
  public int JJT$COMMA = 29;
  public int JJT$VARIABLE = 30;
  public int JJT$INDEX = 31;
  public int JJTEXPR = 32;
  public int JJT$ASSIGN = 33;
  public int JJTEXPR01 = 34;
  public int JJT$QUESTION_MARK = 35;
  public int JJT$COLON = 36;
  public int JJTEXPR02 = 37;
  public int JJT$AND_OR = 38;
  public int JJTEXPR03 = 39;
  public int JJTEXPR04 = 40;
  public int JJTEXPR05 = 41;
  public int JJT$COMPARISON = 42;
  public int JJTEXPR06 = 43;
  public int JJTEXPR07 = 44;
  public int JJT$ARITHMETIC = 45;
  public int JJTEXPR08 = 46;
  public int JJT$SINGLE_SIGN = 47;
  public int JJTEXPR09 = 48;
  public int JJT$EXPO = 49;
  public int JJTEXPR10 = 50;
  public int JJT$UNARY_OP = 51;
  public int JJTEXPR11 = 52;
  public int JJTEXPR12 = 53;
  public int JJTLVALUE = 54;
  public int JJT$CONSTANT = 55;


  public String[] jjtNodeName = {
    "PROGRAM",
    "Instruction",
    "$BEGIN_CURLY",
    "$END_CURLY",
    "$PATTERN",
    "Action",
    "Statement",
    "$ENDLINE",
    "Command",
    "$BEGIN_PARENTHESIS",
    "$END_PARENTHESIS",
    "$IF",
    "$ELSE",
    "$WHILE",
    "$DO_WHILE",
    "$DO",
    "$FOR",
    "$FOR_SEPARATOR",
    "$IN",
    "$ID",
    "Delete",
    "$DELETE",
    "$BEGIN_BRACKET",
    "$END_BRACKET",
    "$EXIT",
    "$RETURN",
    "$PRINT",
    "$GETLINE",
    "Expr_List",
    "$COMMA",
    "$VARIABLE",
    "$INDEX",
    "Expr",
    "$ASSIGN",
    "Expr01",
    "$QUESTION_MARK",
    "$COLON",
    "Expr02",
    "$AND_OR",
    "Expr03",
    "Expr04",
    "Expr05",
    "$COMPARISON",
    "Expr06",
    "Expr07",
    "$ARITHMETIC",
    "Expr08",
    "$SINGLE_SIGN",
    "Expr09",
    "$EXPO",
    "Expr10",
    "$UNARY_OP",
    "Expr11",
    "Expr12",
    "LValue",
    "$CONSTANT",
  };
}
/* JavaCC - OriginalChecksum=635a5541c477d27381c6b99cde8afec0 (do not edit this line) */
